### ISSUE TITLE
Unable to find a destination matching the provided destination specifier

### ISSUE THREAD

**Issue by jcampbell05** [fastlane/scan#97] opened 2016-02-25 07:48 UTC
When running scan, I get.

``` bash
[18:11:20]: ▸ xcodebuild: error: Unable to find a destination matching the provided destination specifier:
[18:11:20]: ▸ { platform:iOS Simulator, id:CE6062D2-735F-4350-9804-A5CB0DE9234C }
```

**Comment by hokster7** [comment] 2016-02-26 03:51
I get this when running on Bitrise. How could I select a suitable test device in a robust way?

**Comment by vpolouchkine** [comment] 2016-02-26 18:47
Looks like this is a dupe of https://github.com/fastlane/scan/issues/17

**Comment by fastlane-bot-helper** [comment] 2016-03-07 20:07
This issue was migrated to https://github.com/fastlane/fastlane/issues/1928. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:

**Closed as completed by fastlane-bot-helper** 2016-03-07 20:07 UTC
Labels: migrated
